os:
  - linux
  - osx
  - windows
language: csharp
mono: none
dotnet: 2.1.402
branches:
  only:
  - master
  - /release-.*/
  - /^\d+\.\d+\.\d+(-\S*)?$/
script: "./build.sh"
git:
  depth: false
